[package]
name = "webrtc-udp-forwarder"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level=3
debug=0
strip="symbols"
lto=true
panic="abort"
codegen-units=1

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
base64 = "0.21.4"
bytes = "1.5.0"
chrono = "0.4.31"
compile-time-run = "0.2.12"
crossbeam-channel = "0.5.8"
crossbeam-queue = "0.3.8"
env_logger = "0.10.0"
futures = "0.3.28"
hex = "0.4.3"
hmac = "0.12.1"
hyper = "0.14.27"
lazy_static = "1.4.0"
log = {version="0.4", features=["release_max_level_info"]}
mimalloc = {version="0.1.39", default-features=false}
parking_lot = "0.12.1"
serde = "1.0.188"
serde_json = "1.0.107"
sha2 = "0.10.8"
tokio = "1.32.0"
toml = "0.8.1"
uds_windows = "1.0.2"
webrtc =  "0.9.0"
websocket = "0.27.0"
#[target.'cfg(unix)'.features]
#openssl = {version = "0.10", features = ["vendored"]}

[patch.crates-io]
webrtc = {path = "webrtc/webrtc/"}
webrtc-sctp = {path = "webrtc/sctp/"}

[features]
tcp=[]
uds=[]
default = ["queuemon"]
queuemon = []
