[package]
name = "webrtc-udp-forwarder"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level=3
debug=0
strip="symbols"
lto=true
panic="abort"
codegen-units=1

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
base64 = "0.21.3"
bytes = "1.4.0"
chrono = "0.4.28"
compile-time-run = "0.2.12"
env_logger = "0.10.0"
futures = "0.3.28"
hex = "0.4.3"
hmac = "0.12.1"
hyper = "0.14.27"
lazy_static = "1.4.0"
log = {version="0.4", features=["release_max_level_info"]}
mimalloc = {version="0.1.38", default-features=false}
parking_lot = "0.12.1"
serde = "1.0.188"
serde_json = "1.0.105"
sha2 = "0.10.7"
tokio = "1.32.0"
toml = "0.7.6"
uds_windows = "1.0.2"
webrtc =  "0.8.0"
websocket = "0.26.5"

[patch.crates-io]
webrtc = {path = "webrtc/webrtc/"}
webrtc-sctp = {path = "webrtc/sctp/"}
