[package]
name = "webrtc-udp-forwarder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
log = "0.4.17"
serde = "1.0.163"
serde_json = "1.0.96"
toml = "0.4.2"
uds_windows = "1.0.2"
webrtc =  "0.7.2"
