[package]
name = "webrtc-udp-forwarder"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level=3
debug=0
strip="symbols"
lto=true
panic="abort"
codegen-units=1

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
base64 = "0.21.0"
bytes = "1.4.0"
chrono = "0.4.24"
env_logger = "0.10.0"
futures = "0.3.28"
lazy_static = "1.4.0"
log = {version="0.4", features=["release_max_level_info"]}
parking_lot = "0.12.1"
serde = "1.0.163"
serde_json = "1.0.96"
tokio = "1.28.1"
toml = "0.4.2"
uds_windows = "1.0.2"
webrtc =  "0.7.2"
