DestinationAddress = "127.0.0.1"
DestinationPort = 8081
AllowedSources = ["127.0.0.0/8", "10.0.0.0/8"]
#AllowedSources = ["10.0.0.0/8"]
ListenAddresses = ["127.0.0.1", "10.0.0.1"]
ListenPort = 8082
TLSServer = true
TLSServerCertPath = "cert.pem"
TLSServerKeyPath = "privkey.pem"
TLSClient = true
AdditionallyValidateAgainstHostname = "testcert.vz.al"
AuthenticateAsClient = true
AuthenticationKeyPSK = "hello"