
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace RV.WebRTCForwarders {
    using System;
    using Terminal.Gui;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class EnterKeyForm : Terminal.Gui.Dialog {
        
        private Terminal.Gui.ColorScheme redOnBlack;
        
        private Terminal.Gui.ColorScheme greenOnBlack;
        
        private Terminal.Gui.ColorScheme greyOnBlack;
        
        private Terminal.Gui.ColorScheme redOnGrey;
        
        private Terminal.Gui.Label keyLabel;
        
        private Terminal.Gui.TextField keyfield;
        
        private Terminal.Gui.Button keyentered;
        
        private Terminal.Gui.Button clear;
        
        private void InitializeComponent() {
            this.clear = new Terminal.Gui.Button();
            this.keyentered = new Terminal.Gui.Button();
            this.keyfield = new Terminal.Gui.TextField();
            this.keyLabel = new Terminal.Gui.Label();
            this.redOnBlack = new Terminal.Gui.ColorScheme(new Terminal.Gui.Attribute(4291104543u, 4278979596u), new Terminal.Gui.Attribute(4291104543u, 4286595104u), new Terminal.Gui.Attribute(4293347414u, 4278979596u), new Terminal.Gui.Attribute(4291611852u, 4278979596u), new Terminal.Gui.Attribute(4293347414u, 4286595104u));
            this.greenOnBlack = new Terminal.Gui.ColorScheme(new Terminal.Gui.Attribute(4279476494u, 4278979596u), new Terminal.Gui.Attribute(4279476494u, 4287109016u), new Terminal.Gui.Attribute(4279682572u, 4278979596u), new Terminal.Gui.Attribute(4291611852u, 4278979596u), new Terminal.Gui.Attribute(4279682572u, 4287109016u));
            this.greyOnBlack = new Terminal.Gui.ColorScheme(new Terminal.Gui.Attribute(4285953654u, 4278979596u), new Terminal.Gui.Attribute(4278979596u, 4285953654u), new Terminal.Gui.Attribute(4285953654u, 4278979596u), new Terminal.Gui.Attribute(4285953654u, 4278979596u), new Terminal.Gui.Attribute(4278979596u, 4285953654u));
            this.redOnGrey = new Terminal.Gui.ColorScheme(new Terminal.Gui.Attribute(4289860911u, 4290889640u), new Terminal.Gui.Attribute(4294111986u, 4291074117u), new Terminal.Gui.Attribute(4294111986u, 4278979596u), new Terminal.Gui.Attribute(4294111986u, 4278979596u), new Terminal.Gui.Attribute(4294111986u, 4278979596u));
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Arrangement = (Terminal.Gui.ViewArrangement.Movable | Terminal.Gui.ViewArrangement.Overlapped);
            this.Modal = false;
            this.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Title = "";
            this.keyLabel.Width = Dim.Auto();
            this.keyLabel.Height = 1;
            this.keyLabel.X = 1;
            this.keyLabel.Y = 1;
            this.keyLabel.Visible = true;
            this.keyLabel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.keyLabel.Data = "keyLabel";
            this.keyLabel.Text = "Key:";
            this.keyLabel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.keyLabel);
            this.keyfield.Width = Dim.Fill(2);
            this.keyfield.Height = 1;
            this.keyfield.X = 27;
            this.keyfield.Y = 1;
            this.keyfield.Visible = true;
            this.keyfield.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.keyfield.Secret = false;
            this.keyfield.Data = "keyfield";
            this.keyfield.Text = "ENTER THE KEY HERE";
            this.keyfield.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.keyfield);
            this.keyentered.Width = Dim.Auto();
            this.keyentered.Height = 1;
            this.keyentered.X = 5;
            this.keyentered.Y = 3;
            this.keyentered.Visible = true;
            this.keyentered.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.keyentered.Data = "keyentered";
            this.keyentered.Text = "That\'s it";
            this.keyentered.TextAlignment = Terminal.Gui.Alignment.Center;
            this.keyentered.IsDefault = false;
            this.Add(this.keyentered);
            this.clear.Width = Dim.Auto();
            this.clear.Height = 1;
            this.clear.X = 28;
            this.clear.Y = 3;
            this.clear.Visible = true;
            this.clear.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.clear.ColorScheme = this.redOnGrey;
            this.clear.Data = "clear";
            this.clear.Text = "Clear All";
            this.clear.TextAlignment = Terminal.Gui.Alignment.Center;
            this.clear.IsDefault = false;
            this.Add(this.clear);
        }
    }
}
