Type = "UDP"
WebRTCMode = "Accept"
Address = "127.0.0.1"
Port = "10012"
ICEServers = [{URLs= ['stun:in.test.vz.al', 'stun:stun.l.google.com']}, {URLs=['turn:in.test.vz.al'], Username='', Credential=''}]
Publish = true
PublishType = "ws"
PublishEndpoint = "wss://vz.al/anonwsmul/xxxx-xxxx-test/wsa"
PublishAuthType = "Basic"
PublishAuthUser = "xxxx"
PublishAuthPass = "xxxx"
PeerAuthType = "PSK"
PeerPSK = "xxxx"
TimeoutCountMax = 3600
ICEListenAddressPort = "0.0.0.0:10011"
