Type = "UDP"
WebRTCMode = "Offer"
Address = "127.0.0.1"
Port = "10500"
ICEServers = [{URLs= ['stun:vz.al', 'stun:stun.l.google.com']}]
Publish = true
PublishType = "ws"
PublishEndpoint = "wss://vz.al/ws1/wso"
PublishAuthType = "Basic"
PublishAuthUser = "xxxx"
PublishAuthPass = "xxxx"
PeerAuthType = "PSK"
PeerPSK = "xxxx"