
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace RV.WebRTCForwarders {
    using System.Security.Cryptography.X509Certificates;
    using Terminal.Gui;
    
    
    public partial class IceCandidateEditor {
        public bool Cancelled = false;
        public IceCandidateEditor() {
            InitializeComponent();
            cancel.Accept += (_, _) => {
                Canceled = true;
                Application.RequestStop();
            };
        }
    }
}
