
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace RV.WebRTCForwarders {
    using System;
    using Terminal.Gui;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class IceCandidateEditor : Terminal.Gui.Dialog {
        
        private Terminal.Gui.ColorScheme redOnBlack;
        
        private Terminal.Gui.ColorScheme greenOnBlack;
        
        private Terminal.Gui.Label serverlabel;
        
        private Terminal.Gui.TextField server;
        
        private Terminal.Gui.Label usernamelabel;
        
        private Terminal.Gui.TextField textField;
        
        private Terminal.Gui.Label credentiallabel;
        
        private Terminal.Gui.TextField credential;
        
        private Terminal.Gui.Button save;
        
        private Terminal.Gui.Button button;
        
        private void InitializeComponent() {
            this.button = new Terminal.Gui.Button();
            this.save = new Terminal.Gui.Button();
            this.credential = new Terminal.Gui.TextField();
            this.credentiallabel = new Terminal.Gui.Label();
            this.textField = new Terminal.Gui.TextField();
            this.usernamelabel = new Terminal.Gui.Label();
            this.server = new Terminal.Gui.TextField();
            this.serverlabel = new Terminal.Gui.Label();
            this.redOnBlack = new Terminal.Gui.ColorScheme(new Terminal.Gui.Attribute(4291104543u, 4278979596u), new Terminal.Gui.Attribute(4291104543u, 4286595104u), new Terminal.Gui.Attribute(4293347414u, 4278979596u), new Terminal.Gui.Attribute(4291611852u, 4278979596u), new Terminal.Gui.Attribute(4293347414u, 4286595104u));
            this.greenOnBlack = new Terminal.Gui.ColorScheme(new Terminal.Gui.Attribute(4279476494u, 4278979596u), new Terminal.Gui.Attribute(4279476494u, 4287109016u), new Terminal.Gui.Attribute(4279682572u, 4278979596u), new Terminal.Gui.Attribute(4291611852u, 4278979596u), new Terminal.Gui.Attribute(4279682572u, 4287109016u));
            this.Width = Dim.Percent(90);
            this.Height = Dim.Percent(80);
            this.X = Pos.Center();
            this.Y = Pos.Center();
            this.Visible = true;
            this.Arrangement = Terminal.Gui.ViewArrangement.Movable;
            this.Modal = true;
            this.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Title = "";
            this.serverlabel.Width = Dim.Auto();
            this.serverlabel.Height = 1;
            this.serverlabel.X = 1;
            this.serverlabel.Y = 0;
            this.serverlabel.Visible = true;
            this.serverlabel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.serverlabel.Data = "serverlabel";
            this.serverlabel.Text = "Server";
            this.serverlabel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.serverlabel);
            this.server.Width = Dim.Fill(5);
            this.server.Height = 1;
            this.server.X = 25;
            this.server.Y = 0;
            this.server.Visible = true;
            this.server.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.server.Secret = false;
            this.server.Data = "server";
            this.server.Text = "turn:in.test.vz.al";
            this.server.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.server);
            this.usernamelabel.Width = Dim.Auto();
            this.usernamelabel.Height = 1;
            this.usernamelabel.X = 1;
            this.usernamelabel.Y = 2;
            this.usernamelabel.Visible = true;
            this.usernamelabel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.usernamelabel.Data = "usernamelabel";
            this.usernamelabel.Text = "Username";
            this.usernamelabel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.usernamelabel);
            this.textField.Width = Dim.Fill(5);
            this.textField.Height = 1;
            this.textField.X = 25;
            this.textField.Y = 2;
            this.textField.Visible = true;
            this.textField.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.textField.Secret = false;
            this.textField.Data = "textField";
            this.textField.Text = "username";
            this.textField.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.textField);
            this.credentiallabel.Width = Dim.Auto();
            this.credentiallabel.Height = 1;
            this.credentiallabel.X = 1;
            this.credentiallabel.Y = 4;
            this.credentiallabel.Visible = true;
            this.credentiallabel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.credentiallabel.Data = "credentiallabel";
            this.credentiallabel.Text = "Password/Credential";
            this.credentiallabel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.credentiallabel);
            this.credential.Width = Dim.Fill(5);
            this.credential.Height = 1;
            this.credential.X = 25;
            this.credential.Y = 4;
            this.credential.Visible = true;
            this.credential.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.credential.Secret = false;
            this.credential.Data = "credential";
            this.credential.Text = "creds";
            this.credential.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.credential);
            this.save.Width = Dim.Auto();
            this.save.Height = 1;
            this.save.X = 11;
            this.save.Y = 6;
            this.save.Visible = true;
            this.save.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.save.ColorScheme = this.greenOnBlack;
            this.save.Data = "save";
            this.save.Text = "Save";
            this.save.TextAlignment = Terminal.Gui.Alignment.Center;
            this.save.IsDefault = false;
            this.Add(this.save);
            this.button.Width = Dim.Auto();
            this.button.Height = 1;
            this.button.X = 26;
            this.button.Y = 6;
            this.button.Visible = true;
            this.button.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.button.ColorScheme = this.redOnBlack;
            this.button.Data = "button";
            this.button.Text = "Cancel";
            this.button.TextAlignment = Terminal.Gui.Alignment.Center;
            this.button.IsDefault = false;
            this.Add(this.button);
        }
    }
}
