
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace RV.WebRTCForwarders {
    using System;
    using Terminal.Gui;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class UtilsForm : Terminal.Gui.Window {
        
        private Terminal.Gui.Button portbasedcalculator;
        
        private void InitializeComponent() {
            this.portbasedcalculator = new Terminal.Gui.Button();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Arrangement = (Terminal.Gui.ViewArrangement.Movable | Terminal.Gui.ViewArrangement.Overlapped);
            this.Modal = false;
            this.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Title = "";
            this.portbasedcalculator.Width = Dim.Auto();
            this.portbasedcalculator.Height = 1;
            this.portbasedcalculator.X = 2;
            this.portbasedcalculator.Y = 1;
            this.portbasedcalculator.Visible = true;
            this.portbasedcalculator.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.portbasedcalculator.Data = "portbasedcalculator";
            this.portbasedcalculator.Text = "Port based address calculator";
            this.portbasedcalculator.TextAlignment = Terminal.Gui.Alignment.Center;
            this.portbasedcalculator.IsDefault = false;
            this.Add(this.portbasedcalculator);
        }
    }
}
