
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace RV.WebRTCForwarders {
    using System;
    using Terminal.Gui;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class Window : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme greenOnBlack;
        
        private Terminal.Gui.ColorScheme tgDefault;
        
        private Terminal.Gui.ColorScheme blueOnBlack;
        
        private Terminal.Gui.ColorScheme redOnBlack;
        
        private Terminal.Gui.ColorScheme greyOnBlack;
        
        private Terminal.Gui.Label filenamelabel;
        
        private Terminal.Gui.Label filename;
        
        private Terminal.Gui.Label endpointtypelabel;
        
        private Terminal.Gui.TextField localtype;
        
        private Terminal.Gui.Label label4;
        
        private Terminal.Gui.RadioGroup webrtcmode;
        
        private Terminal.Gui.Label addrlocallabel;
        
        private Terminal.Gui.TextField textField;
        
        private Terminal.Gui.Label portlabel;
        
        private Terminal.Gui.TextValidateField textValidateField;
        
        private Terminal.Gui.Button button;
        
        private Terminal.Gui.LineView lineView;
        
        private Terminal.Gui.Label tunnelnamelabel;
        
        private Terminal.Gui.TextField tunenlname;
        
        private Terminal.Gui.Label publishlabel;
        
        private Terminal.Gui.RadioGroup radioGroup;
        
        private Terminal.Gui.Label label;
        
        private Terminal.Gui.Label label2;
        
        private Terminal.Gui.Label publishendpointlabel;
        
        private Terminal.Gui.TextField publishendpoint;
        
        private Terminal.Gui.Label publishauthtypelabel;
        
        private Terminal.Gui.RadioGroup radioGroup2;
        
        private Terminal.Gui.Label publishauthuserlabel;
        
        private Terminal.Gui.TextField publishauthuser;
        
        private Terminal.Gui.Label peerauthpasslabel;
        
        private Terminal.Gui.TextField peerauthpass;
        
        private Terminal.Gui.Label peerauthtypelabel;
        
        private Terminal.Gui.TextField peerauthtype;
        
        private Terminal.Gui.TableView tableView;
        
        private Terminal.Gui.Label iceserverslabel;
        
        private Terminal.Gui.Button addicecandidate;
        
        private Terminal.Gui.Button button2;
        
        private Terminal.Gui.Button removeicecandidate;
        
        private Terminal.Gui.MenuBar menuBar;
        
        private Terminal.Gui.MenuBarItem fileF9Menu;
        
        private Terminal.Gui.MenuItem openMenuItem;
        
        private Terminal.Gui.MenuItem saveMenuItem;
        
        private Terminal.Gui.MenuItem saveAsMenuItem;
        
        private Terminal.Gui.MenuItem aboutMenuItem;
        
        private Terminal.Gui.MenuItem exitMenuItem;
        
        private Terminal.Gui.MenuBarItem fileInfoMenu;
        
        private Terminal.Gui.MenuItem editMeMenuItem;
        
        private void InitializeComponent() {
            this.menuBar = new Terminal.Gui.MenuBar();
            this.removeicecandidate = new Terminal.Gui.Button();
            this.button2 = new Terminal.Gui.Button();
            this.addicecandidate = new Terminal.Gui.Button();
            this.iceserverslabel = new Terminal.Gui.Label();
            this.tableView = new Terminal.Gui.TableView();
            this.peerauthtype = new Terminal.Gui.TextField();
            this.peerauthtypelabel = new Terminal.Gui.Label();
            this.peerauthpass = new Terminal.Gui.TextField();
            this.peerauthpasslabel = new Terminal.Gui.Label();
            this.publishauthuser = new Terminal.Gui.TextField();
            this.publishauthuserlabel = new Terminal.Gui.Label();
            this.radioGroup2 = new Terminal.Gui.RadioGroup();
            this.publishauthtypelabel = new Terminal.Gui.Label();
            this.publishendpoint = new Terminal.Gui.TextField();
            this.publishendpointlabel = new Terminal.Gui.Label();
            this.label2 = new Terminal.Gui.Label();
            this.label = new Terminal.Gui.Label();
            this.radioGroup = new Terminal.Gui.RadioGroup();
            this.publishlabel = new Terminal.Gui.Label();
            this.tunenlname = new Terminal.Gui.TextField();
            this.tunnelnamelabel = new Terminal.Gui.Label();
            this.lineView = new Terminal.Gui.LineView();
            this.button = new Terminal.Gui.Button();
            this.textValidateField = new Terminal.Gui.TextValidateField();
            this.portlabel = new Terminal.Gui.Label();
            this.textField = new Terminal.Gui.TextField();
            this.addrlocallabel = new Terminal.Gui.Label();
            this.webrtcmode = new Terminal.Gui.RadioGroup();
            this.label4 = new Terminal.Gui.Label();
            this.localtype = new Terminal.Gui.TextField();
            this.endpointtypelabel = new Terminal.Gui.Label();
            this.filename = new Terminal.Gui.Label();
            this.filenamelabel = new Terminal.Gui.Label();
            this.greenOnBlack = new Terminal.Gui.ColorScheme(new Terminal.Gui.Attribute(4279476494u, 4278979596u), new Terminal.Gui.Attribute(4279476494u, 4287109016u), new Terminal.Gui.Attribute(4279682572u, 4278979596u), new Terminal.Gui.Attribute(4291611852u, 4278979596u), new Terminal.Gui.Attribute(4279682572u, 4287109016u));
            this.tgDefault = new Terminal.Gui.ColorScheme(new Terminal.Gui.Attribute(4294111986u, 4278204378u), new Terminal.Gui.Attribute(4278979596u, 4291611852u), new Terminal.Gui.Attribute(4284602070u, 4278204378u), new Terminal.Gui.Attribute(4286595104u, 4278204378u), new Terminal.Gui.Attribute(4282087679u, 4291611852u));
            this.blueOnBlack = new Terminal.Gui.ColorScheme(new Terminal.Gui.Attribute(4282087679u, 4278979596u), new Terminal.Gui.Attribute(4282087679u, 4294570405u), new Terminal.Gui.Attribute(4282029789u, 4278979596u), new Terminal.Gui.Attribute(4291611852u, 4278979596u), new Terminal.Gui.Attribute(4282029789u, 4294570405u));
            this.redOnBlack = new Terminal.Gui.ColorScheme(new Terminal.Gui.Attribute(4291104543u, 4278979596u), new Terminal.Gui.Attribute(4291104543u, 4286595104u), new Terminal.Gui.Attribute(4293347414u, 4278979596u), new Terminal.Gui.Attribute(4291611852u, 4278979596u), new Terminal.Gui.Attribute(4293347414u, 4286595104u));
            this.greyOnBlack = new Terminal.Gui.ColorScheme(new Terminal.Gui.Attribute(4285953654u, 4278979596u), new Terminal.Gui.Attribute(4278979596u, 4285953654u), new Terminal.Gui.Attribute(4285953654u, 4278979596u), new Terminal.Gui.Attribute(4285953654u, 4278979596u), new Terminal.Gui.Attribute(4278979596u, 4285953654u));
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Arrangement = (Terminal.Gui.ViewArrangement.Movable | Terminal.Gui.ViewArrangement.Overlapped);
            this.ColorScheme = this.greenOnBlack;
            this.Modal = false;
            this.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Title = "";
            this.filenamelabel.Width = Dim.Fill(0);
            this.filenamelabel.Height = 1;
            this.filenamelabel.X = 1;
            this.filenamelabel.Y = 2;
            this.filenamelabel.Visible = true;
            this.filenamelabel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.filenamelabel.Data = "filenamelabel";
            this.filenamelabel.Text = "Filename:";
            this.filenamelabel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.filenamelabel);
            this.filename.Width = Dim.Fill(0);
            this.filename.Height = 1;
            this.filename.X = 30;
            this.filename.Y = 2;
            this.filename.Visible = true;
            this.filename.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.filename.Data = "filename";
            this.filename.Text = "Filename";
            this.filename.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.filename);
            this.endpointtypelabel.Width = Dim.Auto();
            this.endpointtypelabel.Height = 1;
            this.endpointtypelabel.X = 1;
            this.endpointtypelabel.Y = 4;
            this.endpointtypelabel.Visible = true;
            this.endpointtypelabel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.endpointtypelabel.Data = "endpointtypelabel";
            this.endpointtypelabel.Text = "Local Endpoint Type:";
            this.endpointtypelabel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.endpointtypelabel);
            this.localtype.Width = Dim.Fill(5);
            this.localtype.Height = 1;
            this.localtype.X = 30;
            this.localtype.Y = 4;
            this.localtype.Visible = true;
            this.localtype.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.localtype.Secret = false;
            this.localtype.Data = "localtype";
            this.localtype.Text = "UDP";
            this.localtype.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.localtype);
            this.label4.Width = Dim.Auto();
            this.label4.Height = 1;
            this.label4.X = 1;
            this.label4.Y = 6;
            this.label4.Visible = true;
            this.label4.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.label4.Data = "label4";
            this.label4.Text = "WebRTC Mode:";
            this.label4.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.label4);
            this.webrtcmode.Width = 10;
            this.webrtcmode.Height = 2;
            this.webrtcmode.X = 30;
            this.webrtcmode.Y = 6;
            this.webrtcmode.Visible = true;
            this.webrtcmode.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.webrtcmode.Data = "webrtcmode";
            this.webrtcmode.TextAlignment = Terminal.Gui.Alignment.Start;
            this.webrtcmode.RadioLabels = new string[] {
                    "Answer",
                    "Offer"};
            this.Add(this.webrtcmode);
            this.addrlocallabel.Width = Dim.Auto();
            this.addrlocallabel.Height = 1;
            this.addrlocallabel.X = 1;
            this.addrlocallabel.Y = 10;
            this.addrlocallabel.Visible = true;
            this.addrlocallabel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.addrlocallabel.Data = "addrlocallabel";
            this.addrlocallabel.Text = "Address (local)";
            this.addrlocallabel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.addrlocallabel);
            this.textField.Width = Dim.Fill(5);
            this.textField.Height = 2;
            this.textField.X = 30;
            this.textField.Y = 10;
            this.textField.Visible = true;
            this.textField.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.textField.Secret = false;
            this.textField.Data = "textField";
            this.textField.Text = "127.0.0.1";
            this.textField.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.textField);
            this.portlabel.Width = Dim.Auto();
            this.portlabel.Height = 1;
            this.portlabel.X = 1;
            this.portlabel.Y = 12;
            this.portlabel.Visible = true;
            this.portlabel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.portlabel.Data = "portlabel";
            this.portlabel.Text = "Port";
            this.portlabel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.portlabel);
            this.textValidateField.Width = Dim.Fill(5);
            this.textValidateField.Height = 1;
            this.textValidateField.X = 30;
            this.textValidateField.Y = 12;
            this.textValidateField.Visible = true;
            this.textValidateField.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.textValidateField.Provider = new Terminal.Gui.TextValidateProviders.TextRegexProvider(".*");
            this.textValidateField.Data = "textValidateField";
            this.textValidateField.Text = "10010";
            this.textValidateField.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.textValidateField);
            this.button.Width = Dim.Auto();
            this.button.Height = 1;
            this.button.X = 37;
            this.button.Y = 15;
            this.button.Visible = true;
            this.button.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.button.ColorScheme = this.blueOnBlack;
            this.button.Data = "button";
            this.button.Text = "Swap config for the other end";
            this.button.TextAlignment = Terminal.Gui.Alignment.Center;
            this.button.IsDefault = false;
            this.Add(this.button);
            this.lineView.Width = 33;
            this.lineView.Height = 1;
            this.lineView.X = 37;
            this.lineView.Y = 16;
            this.lineView.Visible = true;
            this.lineView.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.lineView.ColorScheme = this.greyOnBlack;
            this.lineView.Data = "lineView";
            this.lineView.TextAlignment = Terminal.Gui.Alignment.Start;
            this.lineView.LineRune = new System.Text.Rune('─');
            this.lineView.Orientation = Terminal.Gui.Orientation.Horizontal;
            this.Add(this.lineView);
            this.tunnelnamelabel.Width = Dim.Auto();
            this.tunnelnamelabel.Height = 1;
            this.tunnelnamelabel.X = 1;
            this.tunnelnamelabel.Y = 19;
            this.tunnelnamelabel.Visible = true;
            this.tunnelnamelabel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.tunnelnamelabel.Data = "tunnelnamelabel";
            this.tunnelnamelabel.Text = "Tunnel name";
            this.tunnelnamelabel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.tunnelnamelabel);
            this.tunenlname.Width = Dim.Fill(5);
            this.tunenlname.Height = 1;
            this.tunenlname.X = 30;
            this.tunenlname.Y = 19;
            this.tunenlname.Visible = true;
            this.tunenlname.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.tunenlname.Secret = false;
            this.tunenlname.Data = "tunenlname";
            this.tunenlname.Text = "name";
            this.tunenlname.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.tunenlname);
            this.publishlabel.Width = Dim.Auto();
            this.publishlabel.Height = 1;
            this.publishlabel.X = 1;
            this.publishlabel.Y = 21;
            this.publishlabel.Visible = true;
            this.publishlabel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.publishlabel.Data = "publishlabel";
            this.publishlabel.Text = "Publish";
            this.publishlabel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.publishlabel);
            this.radioGroup.Width = 10;
            this.radioGroup.Height = 2;
            this.radioGroup.X = 30;
            this.radioGroup.Y = 21;
            this.radioGroup.Visible = true;
            this.radioGroup.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.radioGroup.Data = "radioGroup";
            this.radioGroup.TextAlignment = Terminal.Gui.Alignment.Start;
            this.radioGroup.RadioLabels = new string[] {
                    "True",
                    "False"};
            this.Add(this.radioGroup);
            this.label.Width = Dim.Auto();
            this.label.Height = 1;
            this.label.X = 1;
            this.label.Y = 24;
            this.label.Visible = true;
            this.label.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.label.Data = "label";
            this.label.Text = "PublishType";
            this.label.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.label);
            this.label2.Width = Dim.Fill(0);
            this.label2.Height = 1;
            this.label2.X = 30;
            this.label2.Y = 24;
            this.label2.Visible = true;
            this.label2.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.label2.Data = "label2";
            this.label2.Text = "WSS";
            this.label2.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.label2);
            this.publishendpointlabel.Width = Dim.Auto();
            this.publishendpointlabel.Height = 1;
            this.publishendpointlabel.X = 1;
            this.publishendpointlabel.Y = 26;
            this.publishendpointlabel.Visible = true;
            this.publishendpointlabel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.publishendpointlabel.Data = "publishendpointlabel";
            this.publishendpointlabel.Text = "PublishEndpoint";
            this.publishendpointlabel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.publishendpointlabel);
            this.publishendpoint.Width = Dim.Fill(5);
            this.publishendpoint.Height = 1;
            this.publishendpoint.X = 30;
            this.publishendpoint.Y = 26;
            this.publishendpoint.Visible = true;
            this.publishendpoint.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.publishendpoint.Secret = false;
            this.publishendpoint.Data = "publishendpoint";
            this.publishendpoint.Text = "wss://vz.al/wsanonmul/tunnel_name/wsa";
            this.publishendpoint.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.publishendpoint);
            this.publishauthtypelabel.Width = Dim.Auto();
            this.publishauthtypelabel.Height = 1;
            this.publishauthtypelabel.X = 1;
            this.publishauthtypelabel.Y = 28;
            this.publishauthtypelabel.Visible = true;
            this.publishauthtypelabel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.publishauthtypelabel.Data = "publishauthtypelabel";
            this.publishauthtypelabel.Text = "PublishAuthType";
            this.publishauthtypelabel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.publishauthtypelabel);
            this.radioGroup2.Width = 10;
            this.radioGroup2.Height = 2;
            this.radioGroup2.X = 30;
            this.radioGroup2.Y = 28;
            this.radioGroup2.Visible = true;
            this.radioGroup2.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.radioGroup2.Data = "radioGroup2";
            this.radioGroup2.TextAlignment = Terminal.Gui.Alignment.Start;
            this.radioGroup2.RadioLabels = new string[] {
                    "Basic",
                    "Bearer"};
            this.Add(this.radioGroup2);
            this.publishauthuserlabel.Width = Dim.Auto();
            this.publishauthuserlabel.Height = 1;
            this.publishauthuserlabel.X = 1;
            this.publishauthuserlabel.Y = 32;
            this.publishauthuserlabel.Visible = true;
            this.publishauthuserlabel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.publishauthuserlabel.Data = "publishauthuserlabel";
            this.publishauthuserlabel.Text = "PublishAuthUser";
            this.publishauthuserlabel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.publishauthuserlabel);
            this.publishauthuser.Width = Dim.Fill(5);
            this.publishauthuser.Height = 1;
            this.publishauthuser.X = 30;
            this.publishauthuser.Y = 32;
            this.publishauthuser.Visible = true;
            this.publishauthuser.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.publishauthuser.Secret = false;
            this.publishauthuser.Data = "publishauthuser";
            this.publishauthuser.Text = "username";
            this.publishauthuser.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.publishauthuser);
            this.peerauthpasslabel.Width = Dim.Auto();
            this.peerauthpasslabel.Height = 1;
            this.peerauthpasslabel.X = 1;
            this.peerauthpasslabel.Y = 34;
            this.peerauthpasslabel.Visible = true;
            this.peerauthpasslabel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.peerauthpasslabel.Data = "peerauthpasslabel";
            this.peerauthpasslabel.Text = "PeerAuthPass";
            this.peerauthpasslabel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.peerauthpasslabel);
            this.peerauthpass.Width = Dim.Fill(5);
            this.peerauthpass.Height = 1;
            this.peerauthpass.X = 30;
            this.peerauthpass.Y = 34;
            this.peerauthpass.Visible = true;
            this.peerauthpass.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.peerauthpass.Secret = false;
            this.peerauthpass.Data = "peerauthpass";
            this.peerauthpass.Text = "password";
            this.peerauthpass.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.peerauthpass);
            this.peerauthtypelabel.Width = Dim.Auto();
            this.peerauthtypelabel.Height = 1;
            this.peerauthtypelabel.X = 1;
            this.peerauthtypelabel.Y = 36;
            this.peerauthtypelabel.Visible = true;
            this.peerauthtypelabel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.peerauthtypelabel.Data = "peerauthtypelabel";
            this.peerauthtypelabel.Text = "PeerAuthType";
            this.peerauthtypelabel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.peerauthtypelabel);
            this.peerauthtype.Width = 5;
            this.peerauthtype.Height = 1;
            this.peerauthtype.X = 30;
            this.peerauthtype.Y = 36;
            this.peerauthtype.Visible = true;
            this.peerauthtype.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.peerauthtype.Secret = false;
            this.peerauthtype.Data = "peerauthtype";
            this.peerauthtype.Text = "PSK";
            this.peerauthtype.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.peerauthtype);
            this.tableView.Width = Dim.Fill(5);
            this.tableView.Height = 5;
            this.tableView.X = 30;
            this.tableView.Y = 38;
            this.tableView.Visible = true;
            this.tableView.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.tableView.ColorScheme = this.blueOnBlack;
            this.tableView.Data = "tableView";
            this.tableView.TextAlignment = Terminal.Gui.Alignment.Start;
            this.tableView.FullRowSelect = false;
            this.tableView.Style.AlwaysShowHeaders = false;
            this.tableView.Style.ExpandLastColumn = false;
            this.tableView.Style.InvertSelectedCellFirstCharacter = false;
            this.tableView.Style.ShowHorizontalHeaderOverline = true;
            this.tableView.Style.ShowHorizontalHeaderUnderline = true;
            this.tableView.Style.ShowVerticalCellLines = true;
            this.tableView.Style.ShowVerticalHeaderLines = true;
            System.Data.DataTable tableViewTable;
            tableViewTable = new System.Data.DataTable();
            System.Data.DataColumn tableViewTableURL;
            tableViewTableURL = new System.Data.DataColumn();
            tableViewTableURL.ColumnName = "URL";
            tableViewTable.Columns.Add(tableViewTableURL);
            System.Data.DataColumn tableViewTableUsername;
            tableViewTableUsername = new System.Data.DataColumn();
            tableViewTableUsername.ColumnName = "Username";
            tableViewTable.Columns.Add(tableViewTableUsername);
            System.Data.DataColumn tableViewTableCredential;
            tableViewTableCredential = new System.Data.DataColumn();
            tableViewTableCredential.ColumnName = "Credential";
            tableViewTable.Columns.Add(tableViewTableCredential);
            this.tableView.Table = new Terminal.Gui.DataTableSource(tableViewTable);
            this.Add(this.tableView);
            this.iceserverslabel.Width = Dim.Auto();
            this.iceserverslabel.Height = 1;
            this.iceserverslabel.X = 1;
            this.iceserverslabel.Y = 39;
            this.iceserverslabel.Visible = true;
            this.iceserverslabel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.iceserverslabel.Data = "iceserverslabel";
            this.iceserverslabel.Text = "ICEServers";
            this.iceserverslabel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.iceserverslabel);
            this.addicecandidate.Width = Dim.Auto();
            this.addicecandidate.Height = 1;
            this.addicecandidate.X = 31;
            this.addicecandidate.Y = 46;
            this.addicecandidate.Visible = true;
            this.addicecandidate.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.addicecandidate.Data = "addicecandidate";
            this.addicecandidate.Text = "Add ice candidate";
            this.addicecandidate.TextAlignment = Terminal.Gui.Alignment.Center;
            this.addicecandidate.IsDefault = false;
            this.Add(this.addicecandidate);
            this.button2.Width = Dim.Auto();
            this.button2.Height = 1;
            this.button2.X = 55;
            this.button2.Y = 46;
            this.button2.Visible = true;
            this.button2.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.button2.ColorScheme = this.blueOnBlack;
            this.button2.Data = "button2";
            this.button2.Text = "Edit selected";
            this.button2.TextAlignment = Terminal.Gui.Alignment.Center;
            this.button2.IsDefault = false;
            this.Add(this.button2);
            this.removeicecandidate.Width = Dim.Auto();
            this.removeicecandidate.Height = 1;
            this.removeicecandidate.X = 75;
            this.removeicecandidate.Y = 46;
            this.removeicecandidate.Visible = true;
            this.removeicecandidate.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.removeicecandidate.ColorScheme = this.redOnBlack;
            this.removeicecandidate.Data = "removeicecandidate";
            this.removeicecandidate.Text = "Remove selected";
            this.removeicecandidate.TextAlignment = Terminal.Gui.Alignment.Center;
            this.removeicecandidate.IsDefault = false;
            this.Add(this.removeicecandidate);
            this.menuBar.Width = Dim.Fill(0);
            this.menuBar.Height = 1;
            this.menuBar.X = 0;
            this.menuBar.Y = 0;
            this.menuBar.Visible = true;
            this.menuBar.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.menuBar.Data = "menuBar";
            this.menuBar.TextAlignment = Terminal.Gui.Alignment.Start;
            this.fileF9Menu = new Terminal.Gui.MenuBarItem();
            this.fileF9Menu.Title = "_File (F9)";
            this.openMenuItem = new Terminal.Gui.MenuItem();
            this.openMenuItem.Title = "Open";
            this.openMenuItem.Data = "openMenuItem";
            this.saveMenuItem = new Terminal.Gui.MenuItem();
            this.saveMenuItem.Title = "Save";
            this.saveMenuItem.Data = "saveMenuItem";
            this.saveAsMenuItem = new Terminal.Gui.MenuItem();
            this.saveAsMenuItem.Title = "Save As...";
            this.saveAsMenuItem.Data = "saveAsMenuItem";
            this.aboutMenuItem = new Terminal.Gui.MenuItem();
            this.aboutMenuItem.Title = "About";
            this.aboutMenuItem.Data = "aboutMenuItem";
            this.exitMenuItem = new Terminal.Gui.MenuItem();
            this.exitMenuItem.Title = "Exit";
            this.exitMenuItem.Data = "exitMenuItem";
            this.fileF9Menu.Children = new Terminal.Gui.MenuItem[] {
                    this.openMenuItem,
                    this.saveMenuItem,
                    this.saveAsMenuItem,
                    this.aboutMenuItem,
                    this.exitMenuItem};
            this.fileInfoMenu = new Terminal.Gui.MenuBarItem();
            this.fileInfoMenu.Title = "File info";
            this.editMeMenuItem = new Terminal.Gui.MenuItem();
            this.editMeMenuItem.Title = "Edit Me";
            this.editMeMenuItem.Data = "editMeMenuItem";
            this.fileInfoMenu.Children = new Terminal.Gui.MenuItem[] {
                    this.editMeMenuItem};
            this.menuBar.Menus = new Terminal.Gui.MenuBarItem[] {
                    this.fileF9Menu,
                    this.fileInfoMenu};
            this.Add(this.menuBar);
        }
    }
}
