
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace RV.WebRTCForwarders {
    using System;
    using Terminal.Gui;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class Window : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme greenOnBlack;
        
        private Terminal.Gui.ColorScheme tgDefault;
        
        private Terminal.Gui.ColorScheme blueOnBlack;
        
        private Terminal.Gui.ColorScheme redOnBlack;
        
        private Terminal.Gui.ColorScheme greyOnBlack;
        
        private Terminal.Gui.Label filenamelabel;
        
        private Terminal.Gui.Label filename;
        
        private Terminal.Gui.Label endpointtypelabel;
        
        private Terminal.Gui.TextField localtype;
        
        private Terminal.Gui.Label label4;
        
        private Terminal.Gui.RadioGroup webrtcmode;
        
        private Terminal.Gui.Label addrlocallabel;
        
        private Terminal.Gui.TextField addrlocal;
        
        private Terminal.Gui.Label portlabel;
        
        private Terminal.Gui.TextValidateField portlocal;
        
        private Terminal.Gui.Button button;
        
        private Terminal.Gui.LineView lineView;
        
        private Terminal.Gui.Label tunnelnamelabel;
        
        private Terminal.Gui.TextField tunnelname;
        
        private Terminal.Gui.Label publishlabel;
        
        private Terminal.Gui.RadioGroup whetherpublish;
        
        private Terminal.Gui.Label publishauthtypelabel;
        
        private Terminal.Gui.RadioGroup authtype;
        
        private Terminal.Gui.Button autogenerate;
        
        private Terminal.Gui.Label label;
        
        private Terminal.Gui.Label label2;
        
        private Terminal.Gui.Label publishendpointlabel;
        
        private Terminal.Gui.TextField publishendpoint;
        
        private Terminal.Gui.Label publishauthuserlabel;
        
        private Terminal.Gui.TextField publishauthuser;
        
        private Terminal.Gui.Label publishauthpasslabel;
        
        private Terminal.Gui.TextField publishauthpass;
        
        private Terminal.Gui.Label peerauthtypelabel;
        
        private Terminal.Gui.TextField peerauthtype;
        
        private Terminal.Gui.Label peerpsklabel;
        
        private Terminal.Gui.TextField peerpsk;
        
        private Terminal.Gui.TableView icecandidates;
        
        private Terminal.Gui.Label iceserverslabel;
        
        private Terminal.Gui.Button launchutils;
        
        private Terminal.Gui.Button addicecandidate;
        
        private Terminal.Gui.Button editicecandidate;
        
        private Terminal.Gui.Button removeicecandidate;
        
        private Terminal.Gui.MenuBar menuBar;
        
        private Terminal.Gui.MenuBarItem fileF9Menu;
        
        private Terminal.Gui.MenuItem openMenuItem;
        
        private Terminal.Gui.MenuItem saveMenuItem;
        
        private Terminal.Gui.MenuItem saveAsMenuItem;
        
        private Terminal.Gui.MenuItem aboutMenuItem;
        
        private Terminal.Gui.MenuItem exitMenuItem;
        
        private Terminal.Gui.MenuBarItem fileInfoMenu;
        
        private Terminal.Gui.MenuItem editMeMenuItem;
        
        private void InitializeComponent() {
            this.menuBar = new Terminal.Gui.MenuBar();
            this.removeicecandidate = new Terminal.Gui.Button();
            this.editicecandidate = new Terminal.Gui.Button();
            this.addicecandidate = new Terminal.Gui.Button();
            this.launchutils = new Terminal.Gui.Button();
            this.iceserverslabel = new Terminal.Gui.Label();
            this.icecandidates = new Terminal.Gui.TableView();
            this.peerpsk = new Terminal.Gui.TextField();
            this.peerpsklabel = new Terminal.Gui.Label();
            this.peerauthtype = new Terminal.Gui.TextField();
            this.peerauthtypelabel = new Terminal.Gui.Label();
            this.publishauthpass = new Terminal.Gui.TextField();
            this.publishauthpasslabel = new Terminal.Gui.Label();
            this.publishauthuser = new Terminal.Gui.TextField();
            this.publishauthuserlabel = new Terminal.Gui.Label();
            this.publishendpoint = new Terminal.Gui.TextField();
            this.publishendpointlabel = new Terminal.Gui.Label();
            this.label2 = new Terminal.Gui.Label();
            this.label = new Terminal.Gui.Label();
            this.autogenerate = new Terminal.Gui.Button();
            this.authtype = new Terminal.Gui.RadioGroup();
            this.publishauthtypelabel = new Terminal.Gui.Label();
            this.whetherpublish = new Terminal.Gui.RadioGroup();
            this.publishlabel = new Terminal.Gui.Label();
            this.tunnelname = new Terminal.Gui.TextField();
            this.tunnelnamelabel = new Terminal.Gui.Label();
            this.lineView = new Terminal.Gui.LineView();
            this.button = new Terminal.Gui.Button();
            this.portlocal = new Terminal.Gui.TextValidateField();
            this.portlabel = new Terminal.Gui.Label();
            this.addrlocal = new Terminal.Gui.TextField();
            this.addrlocallabel = new Terminal.Gui.Label();
            this.webrtcmode = new Terminal.Gui.RadioGroup();
            this.label4 = new Terminal.Gui.Label();
            this.localtype = new Terminal.Gui.TextField();
            this.endpointtypelabel = new Terminal.Gui.Label();
            this.filename = new Terminal.Gui.Label();
            this.filenamelabel = new Terminal.Gui.Label();
            this.greenOnBlack = new Terminal.Gui.ColorScheme(new Terminal.Gui.Attribute(4279476494u, 4278979596u), new Terminal.Gui.Attribute(4279476494u, 4287109016u), new Terminal.Gui.Attribute(4279682572u, 4278979596u), new Terminal.Gui.Attribute(4291611852u, 4278979596u), new Terminal.Gui.Attribute(4279682572u, 4287109016u));
            this.tgDefault = new Terminal.Gui.ColorScheme(new Terminal.Gui.Attribute(4294111986u, 4278204378u), new Terminal.Gui.Attribute(4278979596u, 4291611852u), new Terminal.Gui.Attribute(4284602070u, 4278204378u), new Terminal.Gui.Attribute(4286595104u, 4278204378u), new Terminal.Gui.Attribute(4282087679u, 4291611852u));
            this.blueOnBlack = new Terminal.Gui.ColorScheme(new Terminal.Gui.Attribute(4282087679u, 4278979596u), new Terminal.Gui.Attribute(4282087679u, 4294570405u), new Terminal.Gui.Attribute(4282029789u, 4278979596u), new Terminal.Gui.Attribute(4291611852u, 4278979596u), new Terminal.Gui.Attribute(4282029789u, 4294570405u));
            this.redOnBlack = new Terminal.Gui.ColorScheme(new Terminal.Gui.Attribute(4291104543u, 4278979596u), new Terminal.Gui.Attribute(4291104543u, 4286595104u), new Terminal.Gui.Attribute(4293347414u, 4278979596u), new Terminal.Gui.Attribute(4291611852u, 4278979596u), new Terminal.Gui.Attribute(4293347414u, 4286595104u));
            this.greyOnBlack = new Terminal.Gui.ColorScheme(new Terminal.Gui.Attribute(4285953654u, 4278979596u), new Terminal.Gui.Attribute(4278979596u, 4285953654u), new Terminal.Gui.Attribute(4285953654u, 4278979596u), new Terminal.Gui.Attribute(4285953654u, 4278979596u), new Terminal.Gui.Attribute(4278979596u, 4285953654u));
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Arrangement = (Terminal.Gui.ViewArrangement.Movable | Terminal.Gui.ViewArrangement.Overlapped);
            this.ColorScheme = this.greenOnBlack;
            this.Modal = false;
            this.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Title = "";
            this.filenamelabel.Width = Dim.Fill(0);
            this.filenamelabel.Height = 1;
            this.filenamelabel.X = 1;
            this.filenamelabel.Y = 2;
            this.filenamelabel.Visible = true;
            this.filenamelabel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.filenamelabel.Data = "filenamelabel";
            this.filenamelabel.Text = "Filename:";
            this.filenamelabel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.filenamelabel);
            this.filename.Width = Dim.Fill(0);
            this.filename.Height = 1;
            this.filename.X = 30;
            this.filename.Y = 2;
            this.filename.Visible = true;
            this.filename.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.filename.Data = "filename";
            this.filename.Text = "Filename";
            this.filename.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.filename);
            this.endpointtypelabel.Width = Dim.Auto();
            this.endpointtypelabel.Height = 1;
            this.endpointtypelabel.X = 1;
            this.endpointtypelabel.Y = 4;
            this.endpointtypelabel.Visible = true;
            this.endpointtypelabel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.endpointtypelabel.Data = "endpointtypelabel";
            this.endpointtypelabel.Text = "Local Endpoint Type:";
            this.endpointtypelabel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.endpointtypelabel);
            this.localtype.Width = 10;
            this.localtype.Height = 1;
            this.localtype.X = 30;
            this.localtype.Y = 4;
            this.localtype.Visible = true;
            this.localtype.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.localtype.Secret = false;
            this.localtype.Data = "localtype";
            this.localtype.Text = "UDP";
            this.localtype.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.localtype);
            this.label4.Width = Dim.Auto();
            this.label4.Height = 1;
            this.label4.X = 56;
            this.label4.Y = 4;
            this.label4.Visible = true;
            this.label4.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.label4.Data = "label4";
            this.label4.Text = "WebRTC Mode:";
            this.label4.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.label4);
            this.webrtcmode.Width = 10;
            this.webrtcmode.Height = 2;
            this.webrtcmode.X = 76;
            this.webrtcmode.Y = 4;
            this.webrtcmode.Visible = true;
            this.webrtcmode.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.webrtcmode.Data = "webrtcmode";
            this.webrtcmode.TextAlignment = Terminal.Gui.Alignment.Start;
            this.webrtcmode.RadioLabels = new string[] {
                    "Answer",
                    "Offer"};
            this.Add(this.webrtcmode);
            this.addrlocallabel.Width = Dim.Auto();
            this.addrlocallabel.Height = 1;
            this.addrlocallabel.X = 1;
            this.addrlocallabel.Y = 7;
            this.addrlocallabel.Visible = true;
            this.addrlocallabel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.addrlocallabel.Data = "addrlocallabel";
            this.addrlocallabel.Text = "Address (local)";
            this.addrlocallabel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.addrlocallabel);
            this.addrlocal.Width = Dim.Fill(5);
            this.addrlocal.Height = 2;
            this.addrlocal.X = 30;
            this.addrlocal.Y = 7;
            this.addrlocal.Visible = true;
            this.addrlocal.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.addrlocal.Secret = false;
            this.addrlocal.Data = "addrlocal";
            this.addrlocal.Text = "127.0.0.1";
            this.addrlocal.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.addrlocal);
            this.portlabel.Width = Dim.Auto();
            this.portlabel.Height = 1;
            this.portlabel.X = 1;
            this.portlabel.Y = 9;
            this.portlabel.Visible = true;
            this.portlabel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.portlabel.Data = "portlabel";
            this.portlabel.Text = "Port";
            this.portlabel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.portlabel);
            this.portlocal.Width = Dim.Fill(5);
            this.portlocal.Height = 1;
            this.portlocal.X = 30;
            this.portlocal.Y = 9;
            this.portlocal.Visible = true;
            this.portlocal.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.portlocal.Provider = new Terminal.Gui.TextValidateProviders.TextRegexProvider(".*");
            this.portlocal.Data = "portlocal";
            this.portlocal.Text = "10010";
            this.portlocal.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.portlocal);
            this.button.Width = Dim.Auto();
            this.button.Height = 1;
            this.button.X = 37;
            this.button.Y = 11;
            this.button.Visible = true;
            this.button.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.button.ColorScheme = this.blueOnBlack;
            this.button.Data = "button";
            this.button.Text = "Swap config for the other end";
            this.button.TextAlignment = Terminal.Gui.Alignment.Center;
            this.button.IsDefault = false;
            this.Add(this.button);
            this.lineView.Width = 33;
            this.lineView.Height = 1;
            this.lineView.X = 37;
            this.lineView.Y = 12;
            this.lineView.Visible = true;
            this.lineView.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.lineView.ColorScheme = this.greyOnBlack;
            this.lineView.Data = "lineView";
            this.lineView.TextAlignment = Terminal.Gui.Alignment.Start;
            this.lineView.LineRune = new System.Text.Rune('─');
            this.lineView.Orientation = Terminal.Gui.Orientation.Horizontal;
            this.Add(this.lineView);
            this.tunnelnamelabel.Width = Dim.Auto();
            this.tunnelnamelabel.Height = 1;
            this.tunnelnamelabel.X = 1;
            this.tunnelnamelabel.Y = 14;
            this.tunnelnamelabel.Visible = true;
            this.tunnelnamelabel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.tunnelnamelabel.Data = "tunnelnamelabel";
            this.tunnelnamelabel.Text = "Tunnel name";
            this.tunnelnamelabel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.tunnelnamelabel);
            this.tunnelname.Width = Dim.Fill(5);
            this.tunnelname.Height = 1;
            this.tunnelname.X = 30;
            this.tunnelname.Y = 14;
            this.tunnelname.Visible = true;
            this.tunnelname.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.tunnelname.Secret = false;
            this.tunnelname.Data = "tunnelname";
            this.tunnelname.Text = "name";
            this.tunnelname.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.tunnelname);
            this.publishlabel.Width = Dim.Auto();
            this.publishlabel.Height = 1;
            this.publishlabel.X = 1;
            this.publishlabel.Y = 16;
            this.publishlabel.Visible = true;
            this.publishlabel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.publishlabel.Data = "publishlabel";
            this.publishlabel.Text = "Publish";
            this.publishlabel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.publishlabel);
            this.whetherpublish.Width = 10;
            this.whetherpublish.Height = 2;
            this.whetherpublish.X = 30;
            this.whetherpublish.Y = 16;
            this.whetherpublish.Visible = true;
            this.whetherpublish.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.whetherpublish.Data = "whetherpublish";
            this.whetherpublish.TextAlignment = Terminal.Gui.Alignment.Start;
            this.whetherpublish.RadioLabels = new string[] {
                    "True",
                    "False"};
            this.Add(this.whetherpublish);
            this.publishauthtypelabel.Width = Dim.Auto();
            this.publishauthtypelabel.Height = 1;
            this.publishauthtypelabel.X = 52;
            this.publishauthtypelabel.Y = 16;
            this.publishauthtypelabel.Visible = true;
            this.publishauthtypelabel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.publishauthtypelabel.Data = "publishauthtypelabel";
            this.publishauthtypelabel.Text = "PublishAuthType";
            this.publishauthtypelabel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.publishauthtypelabel);
            this.authtype.Width = 10;
            this.authtype.Height = 2;
            this.authtype.X = 77;
            this.authtype.Y = 16;
            this.authtype.Visible = true;
            this.authtype.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.authtype.Data = "authtype";
            this.authtype.TextAlignment = Terminal.Gui.Alignment.Start;
            this.authtype.RadioLabels = new string[] {
                    "Basic",
                    "Bearer"};
            this.Add(this.authtype);
            this.autogenerate.Width = Dim.Auto();
            this.autogenerate.Height = 1;
            this.autogenerate.X = 91;
            this.autogenerate.Y = 16;
            this.autogenerate.Visible = true;
            this.autogenerate.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.autogenerate.Data = "autogenerate";
            this.autogenerate.Text = "Autofill the rest";
            this.autogenerate.TextAlignment = Terminal.Gui.Alignment.Center;
            this.autogenerate.IsDefault = false;
            this.Add(this.autogenerate);
            this.label.Width = Dim.Auto();
            this.label.Height = 1;
            this.label.X = 1;
            this.label.Y = 19;
            this.label.Visible = true;
            this.label.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.label.Data = "label";
            this.label.Text = "PublishType";
            this.label.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.label);
            this.label2.Width = Dim.Fill(0);
            this.label2.Height = 1;
            this.label2.X = 30;
            this.label2.Y = 19;
            this.label2.Visible = true;
            this.label2.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.label2.Data = "label2";
            this.label2.Text = "WSS";
            this.label2.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.label2);
            this.publishendpointlabel.Width = Dim.Auto();
            this.publishendpointlabel.Height = 1;
            this.publishendpointlabel.X = 1;
            this.publishendpointlabel.Y = 21;
            this.publishendpointlabel.Visible = true;
            this.publishendpointlabel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.publishendpointlabel.Data = "publishendpointlabel";
            this.publishendpointlabel.Text = "PublishEndpoint";
            this.publishendpointlabel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.publishendpointlabel);
            this.publishendpoint.Width = Dim.Fill(5);
            this.publishendpoint.Height = 1;
            this.publishendpoint.X = 30;
            this.publishendpoint.Y = 21;
            this.publishendpoint.Visible = true;
            this.publishendpoint.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.publishendpoint.Secret = false;
            this.publishendpoint.Data = "publishendpoint";
            this.publishendpoint.Text = "wss://vz.al/wsanonmul/tunnel_name/wsa";
            this.publishendpoint.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.publishendpoint);
            this.publishauthuserlabel.Width = Dim.Auto();
            this.publishauthuserlabel.Height = 1;
            this.publishauthuserlabel.X = 1;
            this.publishauthuserlabel.Y = 23;
            this.publishauthuserlabel.Visible = true;
            this.publishauthuserlabel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.publishauthuserlabel.Data = "publishauthuserlabel";
            this.publishauthuserlabel.Text = "PublishAuthUser";
            this.publishauthuserlabel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.publishauthuserlabel);
            this.publishauthuser.Width = Dim.Fill(5);
            this.publishauthuser.Height = 1;
            this.publishauthuser.X = 30;
            this.publishauthuser.Y = 23;
            this.publishauthuser.Visible = true;
            this.publishauthuser.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.publishauthuser.Secret = false;
            this.publishauthuser.Data = "publishauthuser";
            this.publishauthuser.Text = "username";
            this.publishauthuser.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.publishauthuser);
            this.publishauthpasslabel.Width = Dim.Auto();
            this.publishauthpasslabel.Height = 1;
            this.publishauthpasslabel.X = 1;
            this.publishauthpasslabel.Y = 25;
            this.publishauthpasslabel.Visible = true;
            this.publishauthpasslabel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.publishauthpasslabel.Data = "publishauthpasslabel";
            this.publishauthpasslabel.Text = "PublishAuthPass";
            this.publishauthpasslabel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.publishauthpasslabel);
            this.publishauthpass.Width = Dim.Fill(5);
            this.publishauthpass.Height = 1;
            this.publishauthpass.X = 30;
            this.publishauthpass.Y = 25;
            this.publishauthpass.Visible = true;
            this.publishauthpass.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.publishauthpass.Secret = false;
            this.publishauthpass.Data = "publishauthpass";
            this.publishauthpass.Text = "password";
            this.publishauthpass.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.publishauthpass);
            this.peerauthtypelabel.Width = Dim.Auto();
            this.peerauthtypelabel.Height = 1;
            this.peerauthtypelabel.X = 1;
            this.peerauthtypelabel.Y = 27;
            this.peerauthtypelabel.Visible = true;
            this.peerauthtypelabel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.peerauthtypelabel.Data = "peerauthtypelabel";
            this.peerauthtypelabel.Text = "PeerAuthType";
            this.peerauthtypelabel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.peerauthtypelabel);
            this.peerauthtype.Width = 6;
            this.peerauthtype.Height = 1;
            this.peerauthtype.X = 30;
            this.peerauthtype.Y = 27;
            this.peerauthtype.Visible = true;
            this.peerauthtype.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.peerauthtype.Secret = false;
            this.peerauthtype.Data = "peerauthtype";
            this.peerauthtype.Text = "PSK";
            this.peerauthtype.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.peerauthtype);
            this.peerpsklabel.Width = Dim.Auto();
            this.peerpsklabel.Height = 1;
            this.peerpsklabel.X = 41;
            this.peerpsklabel.Y = 27;
            this.peerpsklabel.Visible = true;
            this.peerpsklabel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.peerpsklabel.ColorScheme = this.redOnBlack;
            this.peerpsklabel.Data = "peerpsklabel";
            this.peerpsklabel.Text = "PeerPSK (secret)";
            this.peerpsklabel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.peerpsklabel);
            this.peerpsk.Width = Dim.Fill(5);
            this.peerpsk.Height = 1;
            this.peerpsk.X = 62;
            this.peerpsk.Y = 27;
            this.peerpsk.Visible = true;
            this.peerpsk.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.peerpsk.ColorScheme = this.redOnBlack;
            this.peerpsk.Secret = false;
            this.peerpsk.Data = "peerpsk";
            this.peerpsk.Text = "(secret)";
            this.peerpsk.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.peerpsk);
            this.icecandidates.Width = Dim.Fill(5);
            this.icecandidates.Height = 9;
            this.icecandidates.X = 30;
            this.icecandidates.Y = 29;
            this.icecandidates.Visible = true;
            this.icecandidates.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.icecandidates.ColorScheme = this.blueOnBlack;
            this.icecandidates.Data = "icecandidates";
            this.icecandidates.TextAlignment = Terminal.Gui.Alignment.Start;
            this.icecandidates.FullRowSelect = false;
            this.icecandidates.Style.AlwaysShowHeaders = false;
            this.icecandidates.Style.ExpandLastColumn = false;
            this.icecandidates.Style.InvertSelectedCellFirstCharacter = false;
            this.icecandidates.Style.ShowHorizontalHeaderOverline = true;
            this.icecandidates.Style.ShowHorizontalHeaderUnderline = true;
            this.icecandidates.Style.ShowVerticalCellLines = true;
            this.icecandidates.Style.ShowVerticalHeaderLines = true;
            System.Data.DataTable icecandidatesTable;
            icecandidatesTable = new System.Data.DataTable();
            System.Data.DataColumn icecandidatesTableURL;
            icecandidatesTableURL = new System.Data.DataColumn();
            icecandidatesTableURL.ColumnName = "URL";
            icecandidatesTable.Columns.Add(icecandidatesTableURL);
            System.Data.DataColumn icecandidatesTableUsername;
            icecandidatesTableUsername = new System.Data.DataColumn();
            icecandidatesTableUsername.ColumnName = "Username";
            icecandidatesTable.Columns.Add(icecandidatesTableUsername);
            System.Data.DataColumn icecandidatesTableCredential;
            icecandidatesTableCredential = new System.Data.DataColumn();
            icecandidatesTableCredential.ColumnName = "Credential";
            icecandidatesTable.Columns.Add(icecandidatesTableCredential);
            this.icecandidates.Table = new Terminal.Gui.DataTableSource(icecandidatesTable);
            this.Add(this.icecandidates);
            this.iceserverslabel.Width = Dim.Auto();
            this.iceserverslabel.Height = 1;
            this.iceserverslabel.X = 1;
            this.iceserverslabel.Y = 30;
            this.iceserverslabel.Visible = true;
            this.iceserverslabel.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.iceserverslabel.Data = "iceserverslabel";
            this.iceserverslabel.Text = "ICEServers";
            this.iceserverslabel.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.iceserverslabel);
            this.launchutils.Width = Dim.Auto();
            this.launchutils.Height = 1;
            this.launchutils.X = 1;
            this.launchutils.Y = 35;
            this.launchutils.Visible = true;
            this.launchutils.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.launchutils.ColorScheme = this.greyOnBlack;
            this.launchutils.Data = "launchutils";
            this.launchutils.Text = "Utils";
            this.launchutils.TextAlignment = Terminal.Gui.Alignment.Center;
            this.launchutils.IsDefault = false;
            this.Add(this.launchutils);
            this.addicecandidate.Width = Dim.Auto();
            this.addicecandidate.Height = 1;
            this.addicecandidate.X = 31;
            this.addicecandidate.Y = 40;
            this.addicecandidate.Visible = true;
            this.addicecandidate.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.addicecandidate.Data = "addicecandidate";
            this.addicecandidate.Text = "Add ice candidate";
            this.addicecandidate.TextAlignment = Terminal.Gui.Alignment.Center;
            this.addicecandidate.IsDefault = false;
            this.Add(this.addicecandidate);
            this.editicecandidate.Width = Dim.Auto();
            this.editicecandidate.Height = 1;
            this.editicecandidate.X = 55;
            this.editicecandidate.Y = 40;
            this.editicecandidate.Visible = true;
            this.editicecandidate.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.editicecandidate.ColorScheme = this.blueOnBlack;
            this.editicecandidate.Data = "editicecandidate";
            this.editicecandidate.Text = "Edit selected";
            this.editicecandidate.TextAlignment = Terminal.Gui.Alignment.Center;
            this.editicecandidate.IsDefault = false;
            this.Add(this.editicecandidate);
            this.removeicecandidate.Width = Dim.Auto();
            this.removeicecandidate.Height = 1;
            this.removeicecandidate.X = 75;
            this.removeicecandidate.Y = 40;
            this.removeicecandidate.Visible = true;
            this.removeicecandidate.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.removeicecandidate.ColorScheme = this.redOnBlack;
            this.removeicecandidate.Data = "removeicecandidate";
            this.removeicecandidate.Text = "Remove selected";
            this.removeicecandidate.TextAlignment = Terminal.Gui.Alignment.Center;
            this.removeicecandidate.IsDefault = false;
            this.Add(this.removeicecandidate);
            this.menuBar.Width = Dim.Fill(0);
            this.menuBar.Height = 1;
            this.menuBar.X = 0;
            this.menuBar.Y = 0;
            this.menuBar.Visible = true;
            this.menuBar.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.menuBar.Data = "menuBar";
            this.menuBar.TextAlignment = Terminal.Gui.Alignment.Start;
            this.fileF9Menu = new Terminal.Gui.MenuBarItem();
            this.fileF9Menu.Title = "_File (F9)";
            this.openMenuItem = new Terminal.Gui.MenuItem();
            this.openMenuItem.Title = "Open";
            this.openMenuItem.Data = "openMenuItem";
            this.saveMenuItem = new Terminal.Gui.MenuItem();
            this.saveMenuItem.Title = "Save";
            this.saveMenuItem.Data = "saveMenuItem";
            this.saveAsMenuItem = new Terminal.Gui.MenuItem();
            this.saveAsMenuItem.Title = "Save As...";
            this.saveAsMenuItem.Data = "saveAsMenuItem";
            this.aboutMenuItem = new Terminal.Gui.MenuItem();
            this.aboutMenuItem.Title = "About";
            this.aboutMenuItem.Data = "aboutMenuItem";
            this.exitMenuItem = new Terminal.Gui.MenuItem();
            this.exitMenuItem.Title = "Exit";
            this.exitMenuItem.Data = "exitMenuItem";
            this.fileF9Menu.Children = new Terminal.Gui.MenuItem[] {
                    this.openMenuItem,
                    this.saveMenuItem,
                    this.saveAsMenuItem,
                    this.aboutMenuItem,
                    this.exitMenuItem};
            this.fileInfoMenu = new Terminal.Gui.MenuBarItem();
            this.fileInfoMenu.Title = "File info";
            this.editMeMenuItem = new Terminal.Gui.MenuItem();
            this.editMeMenuItem.Title = "Edit Me";
            this.editMeMenuItem.Data = "editMeMenuItem";
            this.fileInfoMenu.Children = new Terminal.Gui.MenuItem[] {
                    this.editMeMenuItem};
            this.menuBar.Menus = new Terminal.Gui.MenuBarItem[] {
                    this.fileF9Menu,
                    this.fileInfoMenu};
            this.Add(this.menuBar);
        }
    }
}
