
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace RV.WebRTCForwarders {
    using Terminal.Gui;
    using Tomlyn.Model;
    using Tomlyn;
    
    
    public partial class Window {
        
        public Window() {
            InitializeComponent();
            Title = $"Configuration Editor ({Application.QuitKey} to Quit)";
            string TomlFileContents = System.IO.File.ReadAllText(StartConfig.Filename);
            var model = Toml.ToModel(TomlFileContents);
            filename.Text = StartConfig.Filename;
            localtype.Enabled = false;
            addicecandidate.MouseClick += (e, a) => {
                Application.Run<IceCandidateEditor>();
            };
        }
    }
}
